### ISSUE TITLE
Small Bug: Wrong links

### ISSUE THREAD

**Issue by ianyepan** [dawranliou/dawranliou.com#13]
Hey, Daw-Ran, I stumbled upon your website today and noticed that you have these two links swapped. Must have been an oversight. Just wanted to give you a heads-up.

![image](https://user-images.githubusercontent.com/36686900/115702239-43578680-a39b-11eb-8f1d-09d4be3b9aeb.png)

**Comment by dawranliou** [comment]
Oh, hey @ianyepan!  Sorry, it took me forever to realize that there has been an issue submitted to this repo!  I sincerely appreciate it 🙇 !

I don't know the exact time/commit I noticed the issue you reported and fixed, but this bug has been addressed. 😉 

I want to take this chance and thank you for your work.  Some of them were great inspirations to me, like the repo [yay-evil-emacs](https://github.com/ianyepan/yay-evil-emacs) and the article on [Moving Away From Oh-My-Zsh](https://ianyepan.github.io/posts/moving-away-from-ohmyzsh/).  Cheers!

**Comment by ianyepan** [comment]
> I want to take this chance and thank you for your work. Some of them were great inspirations to me, like the repo [yay-evil-emacs](https://github.com/ianyepan/yay-evil-emacs) and the article on [Moving Away From Oh-My-Zsh](https://ianyepan.github.io/posts/moving-away-from-ohmyzsh/). Cheers!

Oh I didn't know you read my stuff :) so glad you find them interesting. You just made my day!
